export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    //最热模块 下拉刷新
    POPULAR_REFRESH:'POPULAR_REFRESH',
    LOAD_POPULAR_FAIL:'LOAD_POPULAR_FAIL',   //POPULAR_REFRESH_FAIL
    LOAD_POPULAR_SUCCESS:'LOAD_POPULAR_SUCCESS',   //POPULAR_REFRESH_SUCCESS
    //最热模块 上拉加载更多
    POPULAR_LOAD_MORE_SUCCESS:'POPULAR_LOAD_MORE_SUCCESS',
    POPULAR_LOAD_MORE_FAIL:'POPULAR_LOAD_MORE_SUCCESS',
    //趋势模块
    TRENDING_REFRESH:'TRENDING_REFRESH',
    TRENDING_REFRESH_FAIL:'TRENDING_REFRESH_FAIL',
    TRENDING_REFRESH_SUCCESS:'TRENDING_REFRESH_SUCCESS',
    TRENDING_LOAD_MORE_SUCCESS:'TRENDING_LOAD_MORE_SUCCESS',
    TRENDING_LOAD_MORE_FAIL:'TRENDING_LOAD_MORE_FAIL'
}